name: Test Push

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Create test file
        run: |
          echo "Test push at $(date)" >> test-push.txt
          git add test-push.txt
          git commit -m "Test push commit"
          
      - name: Push to repository
        run: |
          git push origin HEAD:${{ github.ref }}
